---

- name: Update Rocky Linux Servers - Starting Deploy 
  hosts: linux
  tasks:
    - name: DNF | Update System
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: yes

- name: Update Debian Linux Servers - Starting Deploy
  hosts: Linux
  tasks:
    - name: Debian Like | Update System
      ansible.builtin.dnf: name="*" state = latest   

...