---
- name: Testing TAG
  hosts: linux
  tasks: 
   - name: SISOP | Set a hostname 
     ansible.builtin.hostname:
       name: srv01
       use: systemd
     tags: hostname

   - name: SISOP | Disable Selinux (temp)
     ansible.builtin.selinux: state=disabled
     tags: security

   - name: COPY | Copy ansible.cfg
     ansible.builtin.copy:
       src: /etc/ansible/ansible.cfg
       dest: /tmp/ansible.cfg
       owner: root
       mode: 0644
     tags: copy
...